services:
  - type: web
    name: retail-dashboard-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: FRONTEND_ORIGINS
        value: "https://retail-analysis-dashbord-1.onrender.com,http://localhost:5173,http://localhost:3000"
